apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: nginx-deployment
spec:
  #replicas: 2 # tells deployment to run 2 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      annotations:
        ad.datadoghq.com/nginx.check_names: '["nginx"]'
        ad.datadoghq.com/nginx.init_configs: '[{}]'
        ad.datadoghq.com/nginx.instances: '[{"nginx_status_url": "http://%%host%%/nginx_status"}]'
        ad.datadoghq.com/nginx.logs: '[{"source":"nginx","service":"k8s-demo"}]'
      labels:
        role: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-deployment
spec:
  ports:
  - name: nginx
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    role: nginx
  type: LoadBalancer
